[package]
name = "nano_os"
version = "0.1.0"
authors = ["Patrik M. Rosenström <patrik.millvik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pe_parser = { path = "shared/pe_parser" }
dunce = "1.0.1"

